# Generated by Django 4.2.4 on 2023-08-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
